# Generated by Django 3.2 on 2021-04-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('category', models.CharField(max_length=256)),
                ('points', models.IntegerField()),
            ],
        ),
    ]
