# Generated by Django 3.2 on 2021-04-19 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_room_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='timer_expired_count',
            field=models.IntegerField(default=0),
        ),
    ]
