# Generated by Django 3.2 on 2021-04-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_room_timer_expired_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='timer_expired_count',
        ),
        migrations.AddField(
            model_name='room',
            name='is_round_over',
            field=models.BooleanField(default=True),
        ),
    ]
